server.port=8081
spring.application.name=AUTH-SERVICE
spring.datasource.url=jdbc:mysql://mysql-auth:3306/auth_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Priyal212931
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka}
eureka.instance.prefer-ip-address=true
jwt.secret=hms_secret_key_2024_very_long_secure_string
jwt.expiration=86400000
